#!/bin/sh
if ! test -n "$BASH_SOURCE" || ! workdir="${BASH_SOURCE[0]%/*}" || ! test -n "$workdir" || ! cd "$workdir"; then
  workdir=`dirname "$0"` && test -n "$workdir" && cd "$workdir" || echo "Warning: can't get working directory" 1>&2
fi
aclocal -I m4 --install
autoreconf -I m4 -f -i
