/*
  This file is part of GNU libmicrohttpd
  Copyright (C) 2024 Evgeny Grin (Karlson2k)

  GNU libmicrohttpd is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  GNU libmicrohttpd is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
 * @file src/mhd2/tls_dh_params.h
 * @brief  The Diffie-Hellman parameters for TLS backends without RFC7919
 *         support
 * @author Karlson2k (Evgeny Grin)
 */

#ifndef MHD_TLS_DH_PARAMS_H
#define MHD_TLS_DH_PARAMS_H 1

#include "mhd_sys_options.h"

/**
 * The PEM encoded PKCS#3 Diffie-Hellman parameters.
 *
 * To be used only if TLS backend does not support RFC7919 directly.
 * Generated by GnuTLS "certtool --get-dh-params --sec-param=medium" command.
 */
static const char mhd_tls_dh_params_pkcs3[] =
  "-----BEGIN DH PARAMETERS-----\n" \
  "MIIBDAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz\n" \
  "+8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a\n" \
  "87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7\n" \
  "YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi\n" \
  "7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD\n" \
  "ssbzSibBsu/6iGtCOGEoXJf//////////wIBAgICAQA=\n" \
  "-----END DH PARAMETERS-----\n";

#endif /* ! MHD_TLS_DH_PARAMS_H */
