.TH LIBMICROHTTPD "3" "08 Aug 2007" "libmicrohttpd"
.SH "NAME"
libmicrohttpd \- library for embedding HTTP servers
.SH "SYNOPSIS"

\fB#include <microhttpd.h>

.SH "DESCRIPTION"
.P
libmicrohttpd (short MHD) allows applications to easily integrate the functionality of a simple HTTP server.
.P
The details of the API are described in comments in the header file and on the webpage.

.P
.SH "SEE ALSO"
\fBcurl\fP(1), \fBlibcurl\fP(3)

.SH "LEGAL NOTICE"
libmicrohttpd is released under the GPL.

.SH "FILES"
.TP
microhttpd.h
libmicrohttpd include file
.TP
libmicrohttpd.so
libmicrohttpd library

.SH "REPORTING BUGS"
Report bugs by using mantis <https://gnunet.org/mantis/>.

.SH "AUTHORS"
libmicrohttpd was originally designed by Christian Grothoff <christian@grothoff.org> and Chris GauthierDickey <chrisg@cs.du.edu>.  The implementation was done by Daniel Pittman and Christian Grothoff.

.SH "AVAILABILITY"
You can obtain the latest version from http://gnunet.org/libmicrohttpd/.
